export const ROUTES = {
    home: "/",
    archive: "/archive",
    events: "/events",
    eventDetail: (id) => `/events/${id}`,
    projects: "/projects",
    projectDetail: (id) => `/projects/${id}`,
    createProject: "/create-project",
    editProject: (id) => `/edit-project/${id}`,
    admin: "/admin",
    manageDisplay: "/manage-display",
    manageAuthors: "/manage-authors",
    topics: "/specials",
    topicDetail: (id) => `/specials/${id}`,
    createTopic: "/create-special",
    editTopic: (id) => `/edit-special/${id}`,
    postDetail: (id) => `/post/${id}`,
    createPost: "/create-post",
    editPost: (id) => `/edit-post/${id}`,
    addReply: (id) => `/add-reply/${id}`,
    createEvent: "/create-event",
    editEvent: (id) => `/edit-event/${id}`,
};
